@startuml

title ___PROIECT's Class Diagram__\n

  namespace ChestiiRandom {
    class ChestiiRandom.FunctiiStaticeRandom {
    }
  }
  

  namespace ChestiiRandom {
    class ChestiiRandom.MutableBoolean {
    }
  }
  

  namespace Dungeon {
    class Dungeon.Dungeon {
    }
  }
  

  namespace Game {
    class Game.Game {
    }
  }
  

  namespace Game {
    class Game.Window {
    }
  }
  

  namespace Game {
    namespace bject {
      abstract class GameObject.GameObject {
      }
    }
  }
  

  namespace Game {
    namespace bject {
      enum ID {
      }
    }
  }
  

  namespace Handler {
    class Handler.Handler {
    }
  }
  

  namespace Input {
    enum KeyEnum {
    }
  }
  

  namespace Input {
    class Input.KeyInput {
    }
  }
  

  namespace Player {
    class Player.Player {
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Crouch {
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Dash {
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Fall {
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Idle {
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Jump {
      }
    }
  }
  

  namespace Player {
    namespace States {
      abstract class Player.States.PlayerState {
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Walk {
      }
    }
  }
  

  namespace Player {
    class Player.animations_enum {
    }
  }
  

  namespace Room {
    class Room.Room {
    }
  }
  

  namespace SoundTrack {
    class SoundTrack.Music {
    }
  }
  

  namespace SpriteSheet {
    class SpriteSheet.Animation {
    }
  }
  

  namespace SpriteSheet {
    class SpriteSheet.MapSheet {
    }
  }
  

  namespace SpriteSheet {
    class SpriteSheet.SpriteSheet {
    }
  }
  

  namespace SpriteSheet {
    class SpriteSheet.Tile {
    }
  }
  

  Game.Game .up.|> java.lang.Runnable
  Game.Game -up-|> java.awt.Canvas
  Game.Game o-- Handler.Handler : handler
  Game.Game o-- Input.KeyInput : keyInput
  Game.Game o-- SpriteSheet.MapSheet : map_sheet
  Game.Game o-- Game.Window : win
  GameObject.GameObject o-- GameObject.ID : id
  Handler.Handler o-- Dungeon.Dungeon : dungeon
  Input.KeyInput -up-|> java.awt.event.KeyAdapter
  Player.Player -up-|> GameObject.GameObject
  Player.Player o-- SpriteSheet.Animation : currentAnimation
  Player.Player o-- ChestiiRandom.MutableBoolean : inAnimation
  Player.Player o-- Player.States.PlayerState : state
  Player.States.Crouch -up-|> Player.States.PlayerState
  Player.States.Dash -up-|> Player.States.PlayerState
  Player.States.Fall -up-|> Player.States.PlayerState
  Player.States.Idle -up-|> Player.States.PlayerState
  Player.States.Jump -up-|> Player.States.PlayerState
  Player.States.Walk -up-|> Player.States.PlayerState
  Room.Room o-- SpriteSheet.MapSheet : sheet
  SoundTrack.Music .up.|> java.lang.Runnable
  SpriteSheet.Animation -up-|> SpriteSheet.SpriteSheet
  SpriteSheet.MapSheet -up-|> SpriteSheet.SpriteSheet


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
