@startuml

title __STATES's Class Diagram__\n

  namespace Player {
    namespace States {
      class Player.States.Crouch {
          + Crouch()
          + handleInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Dash {
          - prev : int
          + Dash()
          + handleInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Fall {
          + Fall()
          + handleInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Idle {
          + Idle()
          + handleInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Jump {
          + Jump()
          + handleInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      abstract class Player.States.PlayerState {
          {static} # horizontalSpeed : int
          {static} # input : KeyInput
          {static} # verticalSpeed : int
          {abstract} + handleInput()
          {static} + setInput()
      }
    }
  }
  

  namespace Player {
    namespace States {
      class Player.States.Walk {
          + Walk()
          + handleInput()
      }
    }
  }
  

  Player.States.Crouch -up-|> Player.States.PlayerState
  Player.States.Dash -up-|> Player.States.PlayerState
  Player.States.Fall -up-|> Player.States.PlayerState
  Player.States.Idle -up-|> Player.States.PlayerState
  Player.States.Jump -up-|> Player.States.PlayerState
  Player.States.Walk -up-|> Player.States.PlayerState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
